/* Exercise generation and grading.
 *
 * Every item here is produced from the transcribed book content by code, and
 * every graded item is checked by code. Nothing is generated by a model, so an
 * exercise can never invent English that is not in the book, and a right answer
 * can never be marked wrong because a model felt like it.
 *
 * Free translation (the Орчуулга pages) cannot be graded deterministically.
 * Those items are marked selfGraded and are kept out of the accuracy figure.
 */
window.EX = (function () {
  'use strict';

  // -------------------------------------------------------- small helpers
  function hashStr(s) {
    let h = 2166136261;
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }

  function mulberry32(a) {
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function shuffled(arr, rnd) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(rnd() * (i + 1));
      const t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  function norm(s) {
    return String(s)
      .toLowerCase()
      .replace(/[‘’]/g, "'")
      .replace(/[.,;!?]+$/, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  /** Accept "burned / burnt" as burned, burnt, or the whole printed string. */
  function acceptable(answer) {
    const out = [norm(answer)];
    String(answer).split('/').forEach(function (part) {
      const p = norm(part);
      if (p && out.indexOf(p) === -1) out.push(p);
    });
    return out;
  }

  /**
   * Build a 4-way multiple choice. Distractors are drawn from the pool of
   * sibling answers, so every wrong option is real English from the same table.
   * Option order is seeded on the item id and the number of times it has been
   * seen, so the same item does not always show the answer in the same slot.
   */
  function choices(id, answer, pool, n) {
    n = n || 4;
    const seenCount = (window.SRS && SRS.record(id)) ? SRS.record(id).seen : 0;
    const rnd = mulberry32(hashStr(id) + seenCount * 7919);
    const uniq = [];
    pool.forEach(function (p) {
      if (norm(p) !== norm(answer) && uniq.indexOf(p) === -1) uniq.push(p);
    });
    const picked = shuffled(uniq, rnd).slice(0, Math.max(0, n - 1));
    return shuffled(picked.concat([answer]), rnd);
  }

  /** Where an item came from: a book page, or a guide section. */
  function pageRef(unit) {
    const p = unit.pages;
    if (!p || !p.length) return unit.src || '';
    return p.length === 1 ? 'х. ' + p[0] : 'х. ' + p[0] + '–' + p[p.length - 1];
  }

  // ------------------------------------------------------------ generators
  // Each returns an array of item objects.

  function fromPairs(unit, block, bi) {
    const items = [];
    if (!block.drill) return items;
    const ens = block.items.map(function (x) { return x[0]; });
    const mns = block.items.map(function (x) { return x[1]; });
    const dirs = block.drill === 'both' ? ['en_mn', 'mn_en'] : [block.drill];

    block.items.forEach(function (pair, ii) {
      dirs.forEach(function (dir) {
        const id = unit.id + ':' + bi + ':' + ii + ':' + dir;
        if (dir === 'en_mn') {
          items.push({
            id: id, unitId: unit.id, kind: 'choice',
            tag: block.label,
            prompt: pair[0],
            promptNote: 'Энэ үг монголоор юу гэсэн үг вэ?',
            answer: pair[1],
            options: choices(id, pair[1], mns),
            source: pageRef(unit)
          });
        } else {
          items.push({
            id: id, unitId: unit.id, kind: 'choice',
            tag: block.label,
            prompt: pair[1],
            promptNote: 'Which English word is this?',
            answer: pair[0],
            options: choices(id, pair[0], ens),
            source: pageRef(unit)
          });
        }
      });
    });
    return items;
  }

  function fromVerbs(unit, block, bi) {
    const items = [];
    block.items.forEach(function (v, ii) {
      ['pp2', 'pp3'].forEach(function (col) {
        const id = unit.id + ':' + bi + ':' + ii + ':' + col;
        items.push({
          id: id, unitId: unit.id, kind: 'type',
          tag: col === 'pp2' ? 'PP2 — Simple past' : 'PP3 — Past participle',
          prompt: v.v,
          promptNote: v.mn + ' · ' + (col === 'pp2' ? 'Өнгөрсөн цаг (PP2)' : 'Тэгс өнгөрсөн (PP3)'),
          answer: v[col],
          accept: acceptable(v[col]),
          explain: v.v + ' — ' + v.pp2 + ' — ' + v.pp3 + (v.note ? '\n' + v.note : ''),
          source: pageRef(unit)
        });
      });
    });
    return items;
  }

  function fromGrid(unit, block, bi) {
    const items = [];
    const keys = Object.keys(block.cells);
    const allAux = keys.map(function (k) { return block.cells[k].aux; });
    const allFormula = keys.map(function (k) { return block.cells[k].formula; });
    const allNames = keys.map(function (k) { return k.replace('|', ' '); });

    keys.forEach(function (k, ii) {
      const cell = block.cells[k];
      const name = k.replace('|', ' ');

      const idA = unit.id + ':' + bi + ':' + ii + ':aux';
      items.push({
        id: idA, unitId: unit.id, kind: 'choice',
        tag: 'Туслах үйл үг',
        prompt: name,
        promptNote: 'Энэ цагийн туслах үйл үг аль нь вэ?',
        answer: cell.aux,
        options: choices(idA, cell.aux, allAux),
        explain: name + ': ' + cell.formula,
        source: pageRef(unit)
      });

      const idF = unit.id + ':' + bi + ':' + ii + ':formula';
      items.push({
        id: idF, unitId: unit.id, kind: 'choice',
        tag: 'Томьёо',
        prompt: name,
        promptNote: 'Энэ цагийн бүтэц аль нь вэ?',
        answer: cell.formula,
        options: choices(idF, cell.formula, allFormula),
        explain: 'Түлхүүр үг: ' + cell.kw,
        source: pageRef(unit)
      });

      const idT = unit.id + ':' + bi + ':' + ii + ':trans';
      items.push({
        id: idT, unitId: unit.id, kind: 'choice',
        tag: 'Монгол нөхцөл → цаг',
        prompt: cell.trans,
        promptNote: 'Энэ нөхцөл ямар цагийг заана вэ?',
        answer: name,
        options: choices(idT, name, allNames),
        explain: name + ': ' + cell.formula,
        source: pageRef(unit)
      });
    });
    return items;
  }

  function fromSound(unit, block, bi) {
    const items = [];
    const allSounds = block.items.map(function (x) { return x.sound; });

    block.items.forEach(function (s, ii) {
      const idS = unit.id + ':' + bi + ':' + ii + ':spell';
      items.push({
        id: idS, unitId: unit.id, kind: 'choice',
        tag: block.label,
        prompt: s.spelling,
        promptNote: 'Энэ нийлэмж ямар авиа гаргах вэ?',
        answer: s.sound,
        options: choices(idS, s.sound, allSounds),
        explain: 'Жишээ: ' + s.examples.slice(0, 6).join(', ') + (s.note ? '\n' + s.note : ''),
        source: pageRef(unit)
      });

      // One word-level item per spelling rule, so the rule is tested on a word
      // and not only on the abstract letter string.
      const w = s.examples[0];
      const idW = unit.id + ':' + bi + ':' + ii + ':word';
      items.push({
        id: idW, unitId: unit.id, kind: 'choice',
        tag: block.label,
        prompt: w,
        promptNote: 'Энэ үгэнд ямар авиа сонсогдох вэ?',
        answer: s.sound,
        options: choices(idW, s.sound, allSounds),
        explain: s.spelling + ' → ' + s.sound,
        source: pageRef(unit)
      });
    });
    return items;
  }

  function fromPrep(unit, block, bi) {
    const items = [];
    const allPreps = [];
    block.items.forEach(function (p) {
      if (allPreps.indexOf(p.en) === -1) allPreps.push(p.en);
    });

    block.items.forEach(function (p, ii) {
      const id = unit.id + ':' + bi + ':' + ii + ':prep';
      items.push({
        id: id, unitId: unit.id, kind: 'choice',
        tag: block.label,
        prompt: p.ex_mn,
        promptNote: 'Аль угтвар үг таарах вэ?  ___ ' + p.ex_en.replace(/^\S+\s*/, ''),
        answer: p.en,
        options: choices(id, p.en, allPreps),
        explain: p.ex_en + ' — ' + p.ex_mn + '  (' + p.en + ' = ' + p.mn + ')',
        source: pageRef(unit)
      });
    });
    return items;
  }

  function fromMap(unit, block, bi) {
    const items = [];
    const allEn = block.items.map(function (x) { return x.en; });
    const allMn = block.items.map(function (x) { return x.mn; });

    block.items.forEach(function (m, ii) {
      const idF = unit.id + ':' + bi + ':' + ii + ':mn_en';
      items.push({
        id: idF, unitId: unit.id, kind: 'choice',
        tag: 'Монгол нөхцөл → Англи бүтэц',
        prompt: m.mn,
        promptNote: 'Энэ нөхцөлийг англиар ямар бүтцээр илэрхийлэх вэ?',
        answer: m.en,
        options: choices(idF, m.en, allEn),
        explain: '№' + m.n + ': ' + m.mn + ' → ' + m.en,
        source: pageRef(unit)
      });

      const idR = unit.id + ':' + bi + ':' + ii + ':en_mn';
      items.push({
        id: idR, unitId: unit.id, kind: 'choice',
        tag: 'Англи бүтэц → Монгол нөхцөл',
        prompt: m.en,
        promptNote: 'Энэ бүтэц монгол хэлний аль нөхцөлтэй тохирох вэ?',
        answer: m.mn,
        options: choices(idR, m.mn, allMn),
        explain: '№' + m.n + ': ' + m.mn + ' → ' + m.en,
        source: pageRef(unit)
      });
    });
    return items;
  }

  function fromFormula(unit, block, bi) {
    const items = [];
    if (!block.drill) return items;
    const allPatterns = block.items.map(function (x) { return x.pattern; });

    block.items.forEach(function (f, ii) {
      const id = unit.id + ':' + bi + ':' + ii + ':formula';
      items.push({
        id: id, unitId: unit.id, kind: 'choice',
        tag: block.label,
        prompt: f.name,
        promptNote: 'Бүтэц нь юу вэ?',
        answer: f.pattern,
        options: choices(id, f.pattern, allPatterns),
        explain: f.gloss ? f.name + ' /' + f.gloss + '/' : f.name,
        source: pageRef(unit)
      });
    });
    return items;
  }

  function fromTranslate(unit, block, bi) {
    // Not machine-gradable. Offered as self-assessed production practice and
    // excluded from the accuracy figure.
    return block.items.map(function (line, ii) {
      return {
        id: unit.id + ':' + bi + ':' + ii + ':tr',
        unitId: unit.id,
        kind: 'write',
        selfGraded: true,
        tag: block.label,
        prompt: line,
        promptNote: block.dir === 'mn_en'
          ? 'Англиар бичнэ үү.'
          : 'Монголоор бичнэ үү.',
        answer: null,
        source: pageRef(unit)
      };
    });
  }

  /** Flexible question→answer block. Options come from sibling answers. */
  function fromQa(unit, block, bi) {
    const items = [];
    if (!block.drill) return items;
    const pool = block.items.map(function (x) { return x.a; });

    block.items.forEach(function (x, ii) {
      const id = unit.id + ':' + bi + ':' + ii + ':qa';
      items.push({
        id: id, unitId: unit.id, kind: 'choice',
        tag: block.label,
        prompt: x.q,
        promptNote: x.note || '',
        answer: x.a,
        options: choices(id, x.a, pool),
        explain: x.why || '',
        source: unit.src || pageRef(unit)
      });
    });
    return items;
  }

  /**
   * Error-correction drill. The learner retypes the sentence correctly.
   * Typed rather than multiple choice because recognising a correction is much
   * easier than producing one, and these are short enough to type.
   */
  function fromContrast(unit, block, bi) {
    const items = [];
    if (!block.drill) return items;

    block.items.forEach(function (x, ii) {
      const id = unit.id + ':' + bi + ':' + ii + ':fix';
      const accept = [norm(x.good)];
      (x.accept || []).forEach(function (a) {
        if (accept.indexOf(norm(a)) === -1) accept.push(norm(a));
      });
      // Contractions are a formatting choice, not a grammar point here.
      const swapped = norm(x.good).replace(/n't\b/g, ' not');
      if (accept.indexOf(swapped) === -1) accept.push(swapped);

      items.push({
        id: id, unitId: unit.id, kind: 'type',
        tag: block.label,
        prompt: x.bad,
        promptNote: 'Энэ өгүүлбэр буруу. Зөв болгож бичнэ үү.',
        answer: x.good,
        accept: accept,
        explain: '✗ ' + x.bad + '\n✓ ' + x.good + (x.why ? '\n' + x.why : ''),
        source: unit.src || pageRef(unit)
      });
    });
    return items;
  }

  /** Given a word, which sound does it carry? Options are the block's sounds. */
  function fromPron(unit, block, bi) {
    const items = [];
    if (!block.drill) return items;
    const keys = block.items.map(function (x) { return x.key; });

    block.items.forEach(function (s, ii) {
      // Two words per sound, spread across the list so the drill is not all
      // first-listed words.
      [0, Math.min(3, s.words.length - 1)].forEach(function (wi, k) {
        const w = s.words[wi];
        if (!w) return;
        const id = unit.id + ':' + bi + ':' + ii + ':' + k + ':pron';
        items.push({
          id: id, unitId: unit.id, kind: 'choice',
          tag: block.label,
          prompt: w,
          promptNote: 'Энэ үг ямар авиатай вэ?',
          answer: s.key,
          options: choices(id, s.key, keys),
          explain: s.name + ' — ' + s.how +
            (s.pairs && s.pairs.length
              ? '\nХос: ' + s.pairs.map(function (p) { return p[0] + ' / ' + p[1]; }).join(' · ')
              : '') +
            (s.warn ? '\n⚠ ' + s.warn : ''),
          source: unit.src || pageRef(unit)
        });
      });
    });
    return items;
  }

  const GEN = {
    qa: fromQa,
    contrast: fromContrast,
    pron: fromPron,
    pairs: fromPairs,
    verbs: fromVerbs,
    grid: fromGrid,
    sound: fromSound,
    prep: fromPrep,
    map: fromMap,
    formula: fromFormula,
    translate: fromTranslate
  };

  // ---------------------------------------------------------------- public
  const cache = {};

  /** Every graded item for one unit (write items excluded unless asked). */
  function forUnit(unit, opts) {
    opts = opts || {};
    const key = unit.id + (opts.includeWrite ? ':w' : '');
    if (!cache[key]) {
      let out = [];
      unit.blocks.forEach(function (block, bi) {
        const gen = GEN[block.t];
        if (!gen) return;
        if (block.t === 'translate' && !opts.includeWrite) return;
        out = out.concat(gen(unit, block, bi));
      });
      cache[key] = out;
    }
    return cache[key];
  }

  function forUnits(units, opts) {
    let out = [];
    units.forEach(function (u) { out = out.concat(forUnit(u, opts)); });
    return out;
  }

  /** Deterministic grading. Returns {correct, expected}. */
  function check(item, given) {
    if (item.kind === 'write') return { correct: null, expected: null };
    if (item.kind === 'choice') {
      return { correct: norm(given) === norm(item.answer), expected: item.answer };
    }
    const acc = item.accept || acceptable(item.answer);
    return { correct: acc.indexOf(norm(given)) !== -1, expected: item.answer };
  }

  return {
    forUnit: forUnit,
    forUnits: forUnits,
    check: check,
    norm: norm,
    acceptable: acceptable,
    _hash: hashStr
  };
})();
