"""Export the error taxonomy to boldoo/content/taxonomy.js (ADR-0015).

Small Step's learner's-own-errors queue labels code-computed edits from the
SAME closed 24-category enum the journal app uses, with the same treatable /
blocking flags and the same approved rule wording. The taxonomy stays owned
by knowledge/error_taxonomy.yaml and the linguistics-curator; this script
only copies it. Re-run after any taxonomy change, then commit the output.

    python scripts/build_boldoo_taxonomy.py
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "knowledge" / "error_taxonomy.yaml"
OUT = REPO / "boldoo" / "content" / "taxonomy.js"

FIELDS = ("family", "treatable", "blocking", "frequency", "priority",
          "rule_a2", "rule_b1", "bridge", "example")


def main() -> None:
    data = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    cats = {}
    for name, row in data["categories"].items():
        cats[name] = {k: row[k] for k in FIELDS if k in row}
        cats[name].setdefault("treatable", True)
    body = json.dumps({"version": data.get("version", 1),
                       "source": "knowledge/error_taxonomy.yaml",
                       "categories": cats},
                      ensure_ascii=False, indent=2)
    OUT.write_text(
        "/* GENERATED by scripts/build_boldoo_taxonomy.py from\n"
        " * knowledge/error_taxonomy.yaml — do not edit here. The category list\n"
        " * is a CLOSED enum: the labeller may never invent one (ADR-0015). */\n"
        "window.BOLDOO_TAXONOMY = " + body + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(cats)} categories, "
          f"{sum(1 for c in cats.values() if not c['treatable'])} untreatable")


if __name__ == "__main__":
    main()
