"""Export the deterministic patterns to boldoo/content/patterns.js (ADR-0015).

Standing rule 2: code before model. The 64 deterministic patterns run in
Small Step before the corrector — at zero cost, with zero hallucination
risk, and with no key at all.

A pattern earns deterministic status in the parent repo by never firing on
correct English (scripts/validate_patterns.py). That guarantee was proved
under Python regex semantics; this script re-proves it under JavaScript's,
by running every exported pattern in Node:

    1. round-trip   — wrong.replace(find, replace) === right
    2. no self-hit  — find does not match right
    3. zero hits    — find matches nothing in data/clean_english.txt

A pattern that fails any check under JS is DROPPED from the export (and
named), never shipped broken. Re-run after any change to the pattern file,
then commit the output.

    python scripts/build_boldoo_patterns.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "knowledge" / "top_100_patterns.yaml"
CORPUS = REPO / "data" / "clean_english.txt"
OUT = REPO / "boldoo" / "content" / "patterns.js"

_BACKREF = re.compile(r"\\(\d+)")

VALIDATOR = r"""
const [specPath, corpusPath] = process.argv.slice(-2);
const fs = require('fs');
const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
const corpus = fs.readFileSync(corpusPath, 'utf8').split(/\r?\n/);
const bad = [];
for (const p of spec) {
  let re;
  try { re = new RegExp(p.find, p.flags); } catch (e) { bad.push([p.id, 'does not compile: ' + e.message]); continue; }
  const rt = p.wrong.replace(new RegExp(p.find, p.flags + 'g'), p.replace);
  if (rt !== p.right) bad.push([p.id, 'round-trip: ' + JSON.stringify(rt) + ' != ' + JSON.stringify(p.right)]);
  if (re.test(p.right)) bad.push([p.id, 'matches its own corrected form']);
  corpus.forEach((line, i) => { if (re.test(line)) bad.push([p.id, 'FALSE POSITIVE line ' + (i + 1) + ': ' + line.trim()]); });
}
process.stdout.write(JSON.stringify(bad));
"""


def to_js(p: dict) -> dict:
    return {
        "id": p["id"],
        "category": p["category"],
        "severity": p.get("severity", "low"),
        "find": p["find"],
        "flags": "" if p.get("case_sensitive") else "i",
        "replace": _BACKREF.sub(r"$\1", p["replace"]),
        "explanation": p.get("explanation", ""),
        "wrong": p["wrong"],
        "right": p["right"],
    }


def main() -> int:
    data = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    det = [to_js(p) for p in data["patterns"] if p.get("tier") == "deterministic"]

    spec_path = OUT.parent / "_patterns_spec.json"
    spec_path.write_text(json.dumps(det, ensure_ascii=False), encoding="utf-8")
    try:
        proc = subprocess.run(["node", "-e", VALIDATOR, str(spec_path), str(CORPUS)],
                              capture_output=True, text=True, check=True)
    finally:
        spec_path.unlink(missing_ok=True)
    bad = json.loads(proc.stdout)
    dropped = {pid for pid, _ in bad}
    for pid, why in bad:
        print(f"  DROP [{pid}] {why}", file=sys.stderr)

    keep = [{k: v for k, v in p.items() if k not in ("wrong", "right")}
            for p in det if p["id"] not in dropped]
    body = json.dumps({"version": data.get("version", 1),
                       "source": "knowledge/top_100_patterns.yaml",
                       "validated_against": "data/clean_english.txt",
                       "patterns": keep}, ensure_ascii=False, indent=1)
    OUT.write_text(
        "/* GENERATED by scripts/build_boldoo_patterns.py from\n"
        " * knowledge/top_100_patterns.yaml — do not edit here. Every pattern was\n"
        " * re-validated under JavaScript regex semantics: round-trips its own\n"
        " * example and has ZERO hits on data/clean_english.txt (ADR-0015). */\n"
        "window.BOLDOO_PATTERNS = " + body + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(keep)} of {len(det)} deterministic "
          f"patterns ({len(dropped)} dropped under JS)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
