/* GENERATED by scripts/build_boldoo_patterns.py from
 * knowledge/top_100_patterns.yaml — do not edit here. Every pattern was
 * re-validated under JavaScript regex semantics: round-trips its own
 * example and has ZERO hits on data/clean_english.txt (ADR-0015). */
window.BOLDOO_PATTERNS = {
 "version": 1,
 "source": "knowledge/top_100_patterns.yaml",
 "validated_against": "data/clean_english.txt",
 "patterns": [
  {
   "id": 1,
   "category": "articles",
   "severity": "low",
   "find": "\\bI am (geologist|teacher|doctor|nurse|lawyer|journalist|miner|driver)\\b",
   "flags": "",
   "replace": "I am a $1",
   "explanation": "Job words need 'a': I am a geologist."
  },
  {
   "id": 2,
   "category": "articles",
   "severity": "low",
   "find": "\\b(he|she) is (engineer|accountant|economist|architect)\\b",
   "flags": "i",
   "replace": "$1 is an $2",
   "explanation": "Job words need 'an' before a vowel sound: an engineer."
  },
  {
   "id": 3,
   "category": "articles",
   "severity": "low",
   "find": "\\bin mining industry\\b",
   "flags": "i",
   "replace": "in the mining industry",
   "explanation": "Industry names take 'the': the mining industry."
  },
  {
   "id": 6,
   "category": "articles",
   "severity": "low",
   "find": "\\bin the (Mongolia|China|Russia|Japan|Korea|Germany|France|England|America|Australia|Canada)(?=\\s*[.,!?;:]|$)",
   "flags": "i",
   "replace": "in $1",
   "explanation": "Country names take no article: in Mongolia."
  },
  {
   "id": 8,
   "category": "articles",
   "severity": "low",
   "find": "\\bgo(es|ing)? to the work(?= at \\d|\\s*[.,!?])",
   "flags": "i",
   "replace": "go$1 to work",
   "explanation": "Fixed phrase: go to work, no 'the'."
  },
  {
   "id": 10,
   "category": "articles",
   "severity": "low",
   "find": "\\ba (hour|honest|honour|honor)\\b",
   "flags": "i",
   "replace": "an $1",
   "explanation": "'Hour' starts with a vowel SOUND, so: an hour."
  },
  {
   "id": 11,
   "category": "articles",
   "severity": "low",
   "find": "\\ban (universit|uniform|union|unique|united|European)",
   "flags": "i",
   "replace": "a $1",
   "explanation": "'University' starts with a /j/ sound, so: a university."
  },
  {
   "id": 13,
   "category": "plurals",
   "severity": "low",
   "find": "\\b(two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|twenty|thirty|forty|fifty|\\d+) (sample|hole|rock|book|report|test|question|lesson|word|sentence|mistake|hour|minute|month|student|teacher|friend|dog|cat|car|house)(?=\\s*([.,!?;:]|and\\b|or\\b|but\\b)|$)",
   "flags": "i",
   "replace": "$1 $2s",
   "explanation": "After a number, add -s: three samples. English repeats itself."
  },
  {
   "id": 14,
   "category": "countability",
   "severity": "low",
   "find": "\\bmany informations\\b",
   "flags": "i",
   "replace": "much information",
   "explanation": "'Information' never takes -s: much information."
  },
  {
   "id": 15,
   "category": "countability",
   "severity": "low",
   "find": "\\bequipments\\b",
   "flags": "i",
   "replace": "equipment",
   "explanation": "'Equipment' never takes -s."
  },
  {
   "id": 16,
   "category": "countability",
   "severity": "low",
   "find": "\\ban advice\\b",
   "flags": "i",
   "replace": "a piece of advice",
   "explanation": "'Advice' is uncountable: a piece of advice."
  },
  {
   "id": 17,
   "category": "countability",
   "severity": "low",
   "find": "\\bnews are\\b",
   "flags": "i",
   "replace": "news is",
   "explanation": "'News' looks plural but is singular: the news is good."
  },
  {
   "id": 19,
   "category": "countability",
   "severity": "low",
   "find": "\\b(two|three|four|five|many|several|some) researches\\b",
   "flags": "i",
   "replace": "$1 research projects",
   "explanation": "'Research' is uncountable: count it with 'projects' or 'studies'."
  },
  {
   "id": 20,
   "category": "countability",
   "severity": "low",
   "find": "\\bdatas\\b",
   "flags": "i",
   "replace": "data",
   "explanation": "'Data' is already plural — never 'datas'."
  },
  {
   "id": 23,
   "category": "verb_agreement",
   "severity": "low",
   "find": "(^|[.!?]\\s+)(He|She|It) (work|live|come|know|want|need|like|make|take|think|write|read|play|walk|talk|look|seem|feel|eat|run|sleep|speak|drink|start|stay|help|call|tell|give|get|put|sit|stand|open|close|drive|ride|sing|swim|rain|snow)\\b",
   "flags": "",
   "replace": "$1$2 $3s",
   "explanation": "HE-SHE-IT adds -s: he works."
  },
  {
   "id": 24,
   "category": "verb_agreement",
   "severity": "low",
   "find": "\\b(he|she|it) don't\\b",
   "flags": "i",
   "replace": "$1 doesn't",
   "explanation": "he/she/it + doesn't (not don't)."
  },
  {
   "id": 25,
   "category": "tense_aspect",
   "severity": "medium",
   "find": "\\bI work (here|there) since\\b",
   "flags": "i",
   "replace": "I have worked $1 since",
   "explanation": "'since' + still true today → have worked (arrow touching today)."
  },
  {
   "id": 26,
   "category": "tense_aspect",
   "severity": "low",
   "find": "\\b(I am|I'm) knowing\\b",
   "flags": "i",
   "replace": "I know",
   "explanation": "'Know' never takes -ing: I know."
  },
  {
   "id": 27,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(I am|I'm) agree\\b",
   "flags": "i",
   "replace": "I agree",
   "explanation": "'Agree' is a verb, not an adjective: I agree."
  },
  {
   "id": 28,
   "category": "articles",
   "severity": "low",
   "find": "\\b(he|she) is (teacher|geologist|doctor|nurse|lawyer|student)\\b(?! of)",
   "flags": "i",
   "replace": "$1 is a $2",
   "explanation": "Job words need 'a': he is a teacher."
  },
  {
   "id": 30,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(have|has|had) went\\b",
   "flags": "i",
   "replace": "$1 gone",
   "explanation": "have/has/had + gone (third form), never 'went'."
  },
  {
   "id": 31,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(was|were|been|is|are|being) wrote\\b",
   "flags": "i",
   "replace": "$1 written",
   "explanation": "Passive uses the third form: was written."
  },
  {
   "id": 32,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(was|were) happened\\b(?! upon)",
   "flags": "i",
   "replace": "happened",
   "explanation": "'Happen' has no passive: the accident happened."
  },
  {
   "id": 33,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(didn't|did not|don't|doesn't|does not|do not) went\\b",
   "flags": "i",
   "replace": "$1 go",
   "explanation": "After did/didn't the verb goes back to base form: didn't go."
  },
  {
   "id": 34,
   "category": "verb_form",
   "severity": "medium",
   "find": "(^|[.!?]\\s+)(I|He|She|We|They|You|It) (can|must|should|might) to (\\w+)",
   "flags": "",
   "replace": "$1$2 $3 $4",
   "explanation": "After can/must/should: no 'to'. He can swim."
  },
  {
   "id": 35,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\b(he|she|it) cans (drive|go|swim|read|write|speak|work|come|play|walk|run|sing|cook|help)\\b",
   "flags": "i",
   "replace": "$1 can $2",
   "explanation": "Modal verbs never take -s: he can."
  },
  {
   "id": 36,
   "category": "verb_form",
   "severity": "low",
   "find": "\\benjoy(s|ed)? to (work|go|play|read|learn|study|walk|watch|cook|sleep|eat|draw)\\b",
   "flags": "i",
   "replace": "enjoy$1 $2ing",
   "explanation": "enjoy + -ing: enjoy working."
  },
  {
   "id": 37,
   "category": "verb_form",
   "severity": "low",
   "find": "\\blook(s|ing|ed)? forward to (hear|see|meet|discuss|learn|work|read|visit|talk)\\b",
   "flags": "i",
   "replace": "look$1 forward to $2ing",
   "explanation": "'to' here is a preposition → -ing: look forward to hearing."
  },
  {
   "id": 38,
   "category": "verb_form",
   "severity": "medium",
   "find": "\\bsuggest(s|ed)? me to (\\w+)",
   "flags": "i",
   "replace": "suggest$1 that I $2",
   "explanation": "suggest + that + person: he suggested that I go."
  },
  {
   "id": 40,
   "category": "word_choice",
   "severity": "high",
   "find": "\\bI am interesting in\\b(?! (that|my|his|her|their|some|many)\\b)",
   "flags": "",
   "replace": "I am interested in",
   "explanation": "You feel interestED; the thing is interestING."
  },
  {
   "id": 50,
   "category": "prepositions",
   "severity": "medium",
   "find": "\\barriv(ed|es|ing|e) to the\\b(?! (applause|cheers|sound|news|smell|sight|strains|tune|aroma))",
   "flags": "i",
   "replace": "arriv$1 at the",
   "explanation": "arrive AT a place: arrived at the site."
  },
  {
   "id": 51,
   "category": "collocation",
   "severity": "low",
   "find": "\\b(discuss(?:es|ed|ing)?) about\\b",
   "flags": "i",
   "replace": "$1",
   "explanation": "'Discuss' takes no preposition: discuss it."
  },
  {
   "id": 52,
   "category": "collocation",
   "severity": "medium",
   "find": "\\b([Ee]xplain(?:s|ed)?) (me|us) (the|this|that) (\\w+)",
   "flags": "i",
   "replace": "$1 $3 $4 to $2",
   "explanation": "explain something TO someone: explain the data to me."
  },
  {
   "id": 53,
   "category": "prepositions",
   "severity": "low",
   "find": "\\bdepend(s|ed|ing)? of\\b",
   "flags": "i",
   "replace": "depend$1 on",
   "explanation": "depends ON — learn verb + preposition as one chunk."
  },
  {
   "id": 54,
   "category": "collocation",
   "severity": "low",
   "find": "\\blisten(s|ed|ing)? (music|radio|podcasts|songs)\\b",
   "flags": "i",
   "replace": "listen$1 to $2",
   "explanation": "listen TO music."
  },
  {
   "id": 55,
   "category": "prepositions",
   "severity": "low",
   "find": "\\bmarried with (him|her|me)(?=\\s*[.,!?;]|$| for\\b| since\\b| last\\b| in\\b)",
   "flags": "i",
   "replace": "married to $1",
   "explanation": "married TO a person."
  },
  {
   "id": 56,
   "category": "prepositions",
   "severity": "low",
   "find": "\\bin the internet\\b(?! (age|era|world|economy|business|of))",
   "flags": "i",
   "replace": "on the internet",
   "explanation": "ON the internet (like a surface)."
  },
  {
   "id": 60,
   "category": "prepositions",
   "severity": "low",
   "find": "\\bresponsible of\\b",
   "flags": "i",
   "replace": "responsible for",
   "explanation": "responsible FOR something."
  },
  {
   "id": 61,
   "category": "prepositions",
   "severity": "low",
   "find": "\\bon (January|February|March|April|June|July|August|September|October|November|December)\\b(?! \\d|,? the)",
   "flags": "i",
   "replace": "in $1",
   "explanation": "IN a month, ON a date: in July, on July 4."
  },
  {
   "id": 62,
   "category": "collocation",
   "severity": "low",
   "find": "\\benter(s|ed|ing)? into (the|a) (room|building|office|house|hall|kitchen|mine|classroom)\\b",
   "flags": "i",
   "replace": "enter$1 $2 $3",
   "explanation": "'Enter' takes no preposition: enter the room."
  },
  {
   "id": 63,
   "category": "pronoun_gender",
   "severity": "medium",
   "find": "\\b(wife|mother|sister|daughter|grandmother|aunt|girlfriend), he (works|likes|goes|comes|wants|lives|loves|teaches|cooks)\\b",
   "flags": "i",
   "replace": "$1, she $2",
   "explanation": "wife/mother/sister → she. («тэр» hides this choice; English forces it.)"
  },
  {
   "id": 64,
   "category": "determiners",
   "severity": "low",
   "find": "(^|[.!?]\\s+)Its (ready|done|fine|okay|late|good|important)(?=\\s*[.,!?]|$)",
   "flags": "",
   "replace": "$1It's $2",
   "explanation": "it's = it is; its = эзэмшил (possessive)."
  },
  {
   "id": 65,
   "category": "determiners",
   "severity": "low",
   "find": "\\bit's (grade|color|colour|size|shape|name|value|depth|thickness|length|width|own|price|weight)\\b(?! [A-Z])",
   "flags": "",
   "replace": "its $1",
   "explanation": "Possessive is 'its' with no apostrophe: its grade."
  },
  {
   "id": 66,
   "category": "determiners",
   "severity": "low",
   "find": "\\bthe (my|your|his|her|our|their) ([a-z]+)\\b(?!-)",
   "flags": "",
   "replace": "$1 $2",
   "explanation": "Only one pointer word per noun: my report (never 'the my')."
  },
  {
   "id": 67,
   "category": "determiners",
   "severity": "low",
   "find": "\\ba my (friend|colleague|neighbour|neighbor|classmate|relative)\\b",
   "flags": "i",
   "replace": "a $1 of mine",
   "explanation": "'a my friend' → 'a friend of mine'."
  },
  {
   "id": 68,
   "category": "determiners",
   "severity": "low",
   "find": "\\banother (samples|holes|things|books|students|days|reasons|questions|problems|ways|ideas|people|tests|reports)\\b",
   "flags": "i",
   "replace": "other $1",
   "explanation": "'another' + singular; plural takes 'other': other samples."
  },
  {
   "id": 69,
   "category": "determiners",
   "severity": "low",
   "find": "\\b([Ee]very) (student|teacher|worker|day|thing|sample|hole|book|question)s (know|work|like|want|need|make|take|come|get|say|see)\\b",
   "flags": "i",
   "replace": "$1 $2 $3s",
   "explanation": "'every' + singular noun + singular verb: every student knows."
  },
  {
   "id": 70,
   "category": "determiners",
   "severity": "low",
   "find": "\\bsomes\\b",
   "flags": "i",
   "replace": "some",
   "explanation": "'some' never takes -s."
  },
  {
   "id": 71,
   "category": "questions_negation",
   "severity": "medium",
   "find": "(^|[.!?]\\s+)(Where|When|Why|How|What) (you|they|we) (work|live|go|want|study|think|do|come|stay|eat)\\?",
   "flags": "",
   "replace": "$1$2 do $3 $4?",
   "explanation": "Questions borrow 'do': Where do you work?"
  },
  {
   "id": 73,
   "category": "questions_negation",
   "severity": "low",
   "find": "\\b([Dd]o|[Dd]oes|[Dd]id) (he|she|it|you|they|we|I) (work|come|know|want|like|live|make|take|think|read|play|walk|talk|look|seem|feel|run|sleep|speak|drink|start|stay|help|call|tell|give|get|put|sit|stand|open|close|drive|ride|sing|swim)s\\b",
   "flags": "i",
   "replace": "$1 $2 $3",
   "explanation": "'Does' already carries the -s — the verb goes back to base form."
  },
  {
   "id": 74,
   "category": "questions_negation",
   "severity": "high",
   "find": "\\b(asked|wondered|wonder|know|knows|knew) (where|what|when|why|how) did (I|you|he|she|it|we|they) (work|live|stay|play|walk|talk|start|help|call|open|close)\\b",
   "flags": "i",
   "replace": "$1 $2 $3 $4ed",
   "explanation": "Inside a sentence, a question becomes a statement: where I worked."
  },
  {
   "id": 75,
   "category": "questions_negation",
   "severity": "high",
   "find": "\\b(I|you|we|they) no (have|want|need|like|know|work|understand|speak|go)\\b",
   "flags": "i",
   "replace": "$1 don't $2",
   "explanation": "Negation borrows 'do': I don't have."
  },
  {
   "id": 76,
   "category": "questions_negation",
   "severity": "medium",
   "find": "\\b(don't|doesn't|didn't|can't|won't) (have|see|know|want|need|get) no\\b",
   "flags": "i",
   "replace": "$1 $2 any",
   "explanation": "One negative only: don't have ANY."
  },
  {
   "id": 79,
   "category": "capitalization",
   "severity": "low",
   "find": "\\bi (am|was|have|had|will|would|can|could|went|think|want|need|know|like|work|live|go|did|do|see|feel|got)\\b",
   "flags": "",
   "replace": "I $1",
   "explanation": "'I' is always capital."
  },
  {
   "id": 80,
   "category": "capitalization",
   "severity": "low",
   "find": "\\benglish\\b",
   "flags": "",
   "replace": "English",
   "explanation": "Language names are capitalised: English."
  },
  {
   "id": 83,
   "category": "plurals",
   "severity": "low",
   "find": "\\b(a|an) (\\d+)([- ])(metre|meter|kilometre|kilometer|tonne|year|day|week|month|hour|minute|percent)s\\b",
   "flags": "i",
   "replace": "$1 $2$3$4",
   "explanation": "Number + unit before a noun stays singular: a 500-metre hole."
  },
  {
   "id": 85,
   "category": "collocation",
   "severity": "low",
   "find": "\\b(I|you|we|they|he|she) did a (decision|choice|mistake)\\b",
   "flags": "i",
   "replace": "$1 made a $2",
   "explanation": "MAKE a decision (not do)."
  },
  {
   "id": 86,
   "category": "collocation",
   "severity": "low",
   "find": "\\bmake research (on|about|into)\\b",
   "flags": "i",
   "replace": "do research $1",
   "explanation": "DO research (not make)."
  },
  {
   "id": 87,
   "category": "collocation",
   "severity": "low",
   "find": "\\bopen the light(?=\\s*[.,!?]|$| in\\b| for\\b)",
   "flags": "i",
   "replace": "turn on the light",
   "explanation": "TURN ON the light (open is for doors)."
  },
  {
   "id": 88,
   "category": "reported_speech",
   "severity": "low",
   "find": "\\bsaid (me|us) (the|that|what|about)\\b",
   "flags": "i",
   "replace": "told $1 $2",
   "explanation": "TELL + person, SAY + words: he told me."
  },
  {
   "id": 89,
   "category": "word_choice",
   "severity": "low",
   "find": "\\blearned (me|us) (English|Mongolian|math|maths|Russian)\\b",
   "flags": "i",
   "replace": "taught $1 $2",
   "explanation": "The teacher TEACHES; the student LEARNS."
  },
  {
   "id": 94,
   "category": "word_order",
   "severity": "low",
   "find": "\\blook(s|ed|ing)? the (samples|sample|data|equipment|children|kids|patients|plants) after\\b",
   "flags": "i",
   "replace": "look$1 after the $2",
   "explanation": "'look after' stays together: look after the samples."
  },
  {
   "id": 101,
   "category": "countability",
   "severity": "low",
   "find": "\\binformations\\b",
   "flags": "i",
   "replace": "information",
   "explanation": "'Information' never takes -s."
  },
  {
   "id": 102,
   "category": "comparatives",
   "severity": "low",
   "find": "\\bmore (better|worse|easier|bigger|smaller|stronger|faster|cheaper|higher|deeper)\\b",
   "flags": "i",
   "replace": "$1",
   "explanation": "One comparative only: better (never 'more better')."
  }
 ]
};
